name: Generate Lock File and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate_lock_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Dependencies (Generate Lock File)
      run: npm install
    - name: Check if lock file was generated
      run: |
        if [ -f package-lock.json ]; then
          echo "package-lock.json generated successfully"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package-lock.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Generate package-lock.json"
            git push
          fi
        else
          echo "package-lock.json not found"
        fi
    - name: Build
      run: npm run build
